apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sample-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sample-app
  template:
    metadata:
      labels:
        app: redis-sample-app
    spec:
      containers:
      - name: redis-sample-app-container
        image: tripvik1.azurecr.io/redissampleapp:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: redis-sample-app-service
spec:
  selector:
    app: redis-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
